#hasheq((name . "brainfuel")
        (display-name . "BrainFuel")
        (version . "0.2.0")
        (build . 2)
        (macos-icon . "shared/assets/brainfuel.icns")
        (identifier . "site.jrtx.brainfuel")
        (release-channel . stable)
        (linux-icon . "shared/assets/brainfuel-icon-512.png")
        ;; Native Linux installers (deb installs /opt/brainfuel with a
        ;; desktop entry, rpm builds via rpmbuild, AppImage carries its own
        ;; GTK4 closure); the signed tar.gz stays the update-channel payload.
        (linux-formats . ("deb" "rpm" "appimage"))
        (url-schemes . ())
        (file-associations . ())
        (macos-min-version . "14.0")
        (windows-min-version . "10.0.19041.0")
        (backend . "app/backend.rkt")
        (module . "backend")
        (entry . "start")
        (protocol . 1))
