// Generated from shared/i18n/{zh,en}.json — the single i18n source.
// Do not edit; run: node scripts/gen-swift-strings.mjs

enum L10n {
    nonisolated(unsafe) static var language: String = "zh"

    private static let zh: [String: String] = [
    "LblHourly": "5 小时",
    "LblWeekly": "周用量",
    "CardSubtitle": "GLM Coding Plan 额度",
    "QuotaDataStatus": "额度数据",
    "BtnRefreshQuota": "刷新额度",
    "MenuMoreTip": "应用菜单",
    "MenuRefresh": "刷新额度",
    "MenuSettings": "设置…",
    "MenuCheckUpdates": "检查软件更新…",
    "MenuTopmostOn": "置顶显示：开（点击关闭）",
    "MenuTopmostOff": "置顶显示：关（点击开启）",
    "MenuMoveNextDisplay": "移到下一个屏幕",
    "MenuMovePrimary": "移到主屏幕",
    "MenuQuit": "退出",
    "MenuHide": "隐藏到托盘",
    "TrayShow": "显示卡片",
    "TraySettings": "设置…",
    "TrayQuit": "退出",
    "TrayTooltip": "BrainFuel · GLM 额度监控",
    "MenuDetail": "详情…",
    "MenuAccounts": "切换账号",
    "ManageAccounts": "管理账号…",
    "BtnSetActive": "设为当前",
    "AddAccount": "添加账号",
    "RemoveAccount": "删除当前选中账号",
    "LblAccountName": "账号名称（可选，用于区分多个账号）",
    "AccountNamePlaceholder": "例如：工作号",
    "GraphLegendDay": "虚线 = 昨日同期",
    "GraphLegendWeek": "虚线 = 上周同期",
    "MenuMiniMode": "迷你模式",
    "DetailResets": "重置于 {0}",
    "HistoryCollecting": "正在积累用量历史（约 5 分钟一个采样点）…",
    "BurnFaster": "（较 24h 均值快 {0}%）",
    "BurnTypical": "（与 24h 均值持平）",
    "BurnSlower": "（较 24h 均值慢 {0}%）",
    "TipHourly": "5 小时 · 已用 {0}%",
    "TipWeekly": "周额度 · 已用 {0}%",
    "TipBurn": "燃速 ≈{0}%/时 · 预计 {1} 后耗尽",
    "TipSizeHint": "单击卡片查看详情，双击切换迷你",
    "NotifyHourlyBody1": "5 小时额度已烧 {0}%——踩一脚刹车 🔥",
    "NotifyHourlyBody2": "额度消耗有点猛，悠着点 ⚡",
    "NotifyHourlyBody3": "5 小时窗口快见底了，省着点用",
    "NotifyWeeklyBody1": "周额度已烧 {0}%——本周余量要精打细算了 📉",
    "NotifyWeeklyBody2": "周额度逼近阈值，长任务悠着点",
    "NotifyWeeklyBody3": "一周额度烧掉 {0}%，大任务悠着点",
    "NotifyBurnSuffix": "\n按当前燃速，约 {0} 后耗尽",
    "HiddenTitle": "已隐藏到托盘",
    "HiddenBody": "额度监控仍在后台运行。点击托盘图标恢复卡片，右键托盘图标可退出。",
    "ErrLogAt": "详细日志：{0}",
    "WinTitle": "BrainFuel 设置",
    "SettingsTitle": "GLM 套餐额度监控",
    "SettingsDesc": "GLM Coding Plan 额度、桌面行为、通知与软件更新",
    "SectionHotkey": "全局快捷键",
    "ChkHotkey": "启用显示/隐藏卡片快捷键",
    "HotkeyHint": "如 Ctrl+Alt+B（字母 / 数字 / F1-F24，至少一个修饰键）",
    "HotkeyInvalid": "快捷键格式无效，已保留原设置",
    "DiagnosticsTitle": "问题反馈",
    "DiagnosticsHint": "遇到问题时，复制诊断信息（版本、账号设置、失败日志；不含 Key 和额度数据）粘贴给开发者即可快速定位。",
    "DiagnosticsCopy": "复制诊断信息 →",
    "DiagnosticsCopied": "已复制到剪贴板，粘贴给开发者即可。",
    "DiagnosticsCopyFailed": "复制失败，请手动截图设置页。",
    "TabGeneral": "常规",
    "TabAccount": "账户",
    "TabNotifications": "通知",
    "TabSoftware": "软件",
    "SectionAppearance": "外观",
    "SectionDesktopBehavior": "桌面行为",
    "SectionQuotaDisplay": "额度显示",
    "SectionStartup": "启动",
    "SectionAccount": "GLM 账户",
    "AccountDesc": "Key 仅用于向你选择的 GLM 平台查询 Coding Plan 额度；BrainFuel 会优先使用系统安全存储，而不是把 Key 明文写入设置文件。",
    "CredentialSecurityTitle": "API Key 安全存储",
    "CredentialProtected": "{0} 正在保护你的 API Key；settings.json 不再保存明文 Key。",
    "CredentialUnavailable": "已保存的 API Key 仍由 {0} 保护，但系统安全存储当前暂时不可访问。BrainFuel 不会把它降级写回明文；后续刷新会自动重试读取。",
    "CredentialFallback": "系统安全存储当前不可用，Key 暂时保存在仅当前用户可读的 settings.json 中。建议启用系统密钥环后重新保存。",
    "CredentialEmpty": "保存 Key 时会优先使用 {0}；不可用时才使用受限权限的本地设置文件。",
    "CredentialForget": "忘记已保存的 API Key",
    "CredentialPendingClear": "保存后将删除 BrainFuel 记录的 API Key。即使系统密钥环当前不可访问，也不会在以后重新恢复旧 Key。",
    "SectionNotifications": "额度提醒",
    "NotificationsDesc": "当额度接近耗尽时显示本地桌面通知。",
    "SoftwareDesc": "这里管理 BrainFuel 自身版本；与“刷新额度”完全独立。",
    "SoftwareTrustTitle": "开源与发布可信度",
    "SoftwareTrustDesc": "正式版本由 GitHub Actions 构建，Release 提供 SHA256SUMS 与 Artifact Attestation。Windows 未购买商业代码签名，因此仍可能出现 SmartScreen 提示。",
    "FirstRunTitle": "快速上手",
    "FirstRunBody": "粘贴 GLM Coding Plan Key 并保存后，主卡片会开始显示额度。主卡片底部的“刷新额度”只刷新额度数据；设置、软件更新、屏幕移动与关于位于右上角“⋯”应用菜单。",
    "KeyHint": "GLM Coding Plan 专用 Key，与 glm-plan-usage 插件同款",
    "KeyOpenConsole": "打开控制台获取 →",
    "ValidateTesting": "验证中…",
    "ValidateSaveAnyway": "仍然保存并应用",
    "ValidateBadKey": "Key 验证失败（HTTP {0}）— 请检查 Key 与平台是否匹配",
    "ValidateNetwork": "连接失败 — 请检查网络；也可先保存，联网后自动刷新",
    "NotConfigured": "未配置，点击设置",
    "CredentialUnavailableCard": "系统凭据暂时不可用",
    "LblLanguage": "语言",
    "LblTheme": "主题",
    "ThemeSystem": "跟随系统",
    "ThemeLight": "亮色",
    "ThemeDark": "暗色",
    "LblOpacity": "卡片透明度",
    "LblRingPalette": "圆环配色",
    "PaletteHint": "点击即时预览；保存后生效。告急的琥珀/红色不随配色变化。",
    "ChkAlwaysOnTop": "置顶显示卡片",
    "AlwaysOnTopHint": "开启后卡片会保持在其他窗口上方；关闭后它会像普通窗口一样被正在使用的应用覆盖，更不容易打扰工作。",
    "PlacementHint": "会记住卡片所在屏幕和相对位置。外接屏拔掉时自动迁回主屏；重新接入后不会突然跳回。分辨率、DPI 或任务栏变化时也会把整张卡片保持在可见区域。",
    "LblApiKey": "API Key",
    "KeyPlaceholder": "粘贴 GLM Coding Plan Key",
    "LblPlatform": "平台",
    "PlatformCn": "智谱国内 · open.bigmodel.cn",
    "PlatformIntl": "Z.ai 国际 · api.z.ai",
    "PlatformCodex": "Codex · 本机登录",
    "PlatformClaude": "Claude · 本机登录",
    "CliLoginHint": "Codex / Claude 账号无需粘贴 Key：BrainFuel 直接读取本机 CLI（~/.codex、~/.claude）的登录凭据，登录状态随 CLI 自动更新。",
    "CliLoginMissing": "未检测到本机 {0} 登录，无法保存该账号。",
    "LblInterval": "自动刷新间隔",
    "UnitMinutes": "分钟",
    "IntervalInputHint": "可直接输入 1–60；输入后按 Enter 或点击空白处确认，也可使用快捷值。",
    "IntervalActiveStatus": "✓ 当前生效：每 {0} 分钟刷新额度",
    "IntervalPendingStatus": "待保存：每 {0} 分钟刷新额度。点击“保存并应用”后生效。",
    "ChkWeeklyRemaining": "周用量显示「剩余」而非「已用」",
    "ChkHourlyRemaining": "5 小时显示「剩余」而非「已用」",
    "ChkAutostart": "开机自动启动 BrainFuel",
    "ChkNotify": "额度接近耗尽时桌面通知",
    "LblThreshold": "触发阈值（已用 %）",
    "BtnCancel": "取消",
    "BtnOK": "好",
    "BtnSave": "保存并应用",
    "UpdateSectionTitle": "BrainFuel 软件更新",
    "UpdateCurrentVersion": "当前版本：v{0}",
    "UpdateInstalledBuild": "Windows 安装版",
    "UpdatePortableBuild": "便携版",
    "BtnCheckUpdates": "检查软件更新",
    "UpdateChecking": "正在检查软件更新…",
    "UpdateDownloading": "正在下载软件更新…",
    "UpdateDownloadPercent": "正在下载软件更新… {0}%",
    "UpdateDownloaded": "更新已下载",
    "UpdateRestarting": "正在安装并重启 BrainFuel…",
    "UpdateAvailableTitle": "发现新版本",
    "UpdateAvailableBody": "新版本 {0} 可用，是否立即更新并重启？",
    "UpdateRestart": "立即更新",
    "UpdateQuitAndInstall": "退出并安装",
    "UpdateReadyBody": "新版本已就绪，BrainFuel 将重启完成安装。",
    "UpdateUpToDate": "BrainFuel 已是最新版本",
    "UpdateCheckFailed": "检查更新失败：{0}",
    "UpdateInstallFailed": "安装更新失败：{0}。当前版本未受影响。",
    "UpdateNotInstalled": "当前为开发副本，自动更新不可用。",
    "UpdateMsiInstalled": "当前副本通过 MSI 安装器安装，应用内更新暂不可用，请到发布页下载新安装包。",
    "UpdateInstalledOnly": "便携版不会自更新：请从 Releases 下载新压缩包，解压后覆盖当前目录。",
    "UpdatePortableHint": "便携版更新方式：从 Releases 下载新压缩包，解压覆盖当前目录；应用内更新随版本一同发布。",
    "UpdateOpenDownloads": "查看 Releases 与下载 →",
    "UpdateOpenReleases": "打开发布页",
    "UpdateInstallHint": "安装方法：解压下载的压缩包，覆盖当前 BrainFuel 目录。",
    "UpdateOpenFolder": "打开文件夹",
    "UpdateFailed": "软件更新检查失败，请稍后重试",
    "UpdateCheckingShort": "检查中…",
    "UpdateDownloadingShort": "下载中…",
    "UpdateRestartingShort": "安装中…",
    "UpdateUpToDateShort": "已是最新",
    "UpdatePortableShort": "便携版",
    "UpdateFailedShort": "更新失败",
    "JustNow": "刚刚",
    "MinutesAgo": "{0} 分钟前",
    "HoursAgo": "{0} 小时前",
    "DaysAgo": "{0} 天前",
    "Refreshing": "正在刷新额度…",
    "RefreshFailed": "额度刷新失败",
    "RefreshFailedAt": "刷新失败 · 上次 {0}",
    "MinutesLater": "{0} 分钟后",
    "HoursLater": "{0} 小时后",
    "DaysLater": "{0} 天后",
    "ResettingSoon": "即将重置",
    "None": "—",
    "NotifyHourlyTitle": "5 小时额度即将耗尽",
    "NotifyWeeklyTitle": "周额度即将耗尽",
    "NotifyUsed": "已用 {0}%",
    "FailureAuthentication": "API Key 无效或平台不匹配",
    "FailureNetwork": "网络连接失败",
    "FailureTls": "TLS / 证书连接失败",
    "FailureProxy": "代理连接失败",
    "FailureTimeout": "连接超时",
    "FailureRateLimited": "请求过于频繁，稍后重试",
    "FailureNoCodingPlan": "账户未开通 Coding Plan",
    "FailureServiceUnavailable": "GLM 服务暂时异常",
    "FailureInvalidResponse": "GLM 返回数据无法识别",
    "FailureUnknown": "额度刷新失败",
    "ValidationAuthentication": "API Key 无效，或所选平台与 Key 不匹配。请检查 Key，并确认“智谱国内 / Z.ai 国际”选择正确。",
    "ValidationNetwork": "无法连接 GLM 服务。请检查网络后重试；也可以先保存，联网后 BrainFuel 会自动刷新。",
    "ValidationTls": "TLS / 证书握手失败。请检查系统时间、系统证书，或公司网络是否拦截 HTTPS。",
    "ValidationProxy": "代理连接失败。请检查 Windows / 系统代理、公司代理或 VPN 设置。",
    "ValidationTimeout": "连接 GLM 服务超时。请检查网络、代理或稍后重试。",
    "ValidationRateLimited": "GLM 暂时限流了这个请求。请稍后重试；当前设置可以先保存。",
    "ValidationNoCodingPlan": "这个账户没有检测到可用的 Coding Plan 额度。请确认该 Key 属于已开通 GLM Coding Plan 的账户；如果是刚购买的新套餐，可能是监控接口暂未覆盖，可选择保存并持续刷新观察。",
    "ValidationServiceUnavailable": "GLM 服务当前暂时异常。请稍后重试；当前设置可以先保存。",
    "ValidationInvalidResponse": "GLM 返回了 BrainFuel 无法识别的数据，可能是接口临时变化。可以先保存设置并稍后重试。",
    "ValidationUnknown": "额度验证失败。可以先保存设置并稍后重试。",
    ]

    private static let en: [String: String] = [
    "LblHourly": "5 hours",
    "LblWeekly": "Weekly",
    "CardSubtitle": "GLM Coding Plan quota",
    "QuotaDataStatus": "Quota data",
    "BtnRefreshQuota": "Refresh quota",
    "MenuMoreTip": "App menu",
    "MenuRefresh": "Refresh quota",
    "MenuSettings": "Settings…",
    "MenuCheckUpdates": "Check software updates…",
    "MenuTopmostOn": "Keep on top: On (click to disable)",
    "MenuTopmostOff": "Keep on top: Off (click to enable)",
    "MenuMoveNextDisplay": "Move to next display",
    "MenuMovePrimary": "Move to primary display",
    "MenuQuit": "Quit",
    "MenuHide": "Hide to tray",
    "TrayShow": "Show widget",
    "TraySettings": "Settings…",
    "TrayQuit": "Quit",
    "TrayTooltip": "BrainFuel · GLM quota monitor",
    "MenuDetail": "Details…",
    "MenuAccounts": "Switch account",
    "ManageAccounts": "Manage accounts…",
    "BtnSetActive": "Set active",
    "AddAccount": "Add account",
    "RemoveAccount": "Remove selected account",
    "LblAccountName": "Account name (optional, to tell accounts apart)",
    "AccountNamePlaceholder": "e.g. Work",
    "GraphLegendDay": "dashed = same time yesterday",
    "GraphLegendWeek": "dashed = same week last week",
    "MenuMiniMode": "Mini mode",
    "DetailResets": "resets {0}",
    "HistoryCollecting": "Collecting usage history (one sample every ~5 min)…",
    "BurnFaster": " (faster than the 24h average by {0}%)",
    "BurnTypical": " (in line with the 24h average)",
    "BurnSlower": " (slower than the 24h average by {0}%)",
    "TipHourly": "5-hour · {0}% used",
    "TipWeekly": "Weekly · {0}% used",
    "TipBurn": "Burn ≈{0}%/h · empty in about {1}",
    "TipSizeHint": "Click for details, double-click for mini",
    "NotifyHourlyBody1": "The 5-hour window is {0}% burned — ease off 🔥",
    "NotifyHourlyBody2": "Burning fast — maybe cool it ⚡",
    "NotifyHourlyBody3": "5-hour quota running low, pace yourself",
    "NotifyWeeklyBody1": "Weekly quota is {0}% burned — budget the rest 📉",
    "NotifyWeeklyBody2": "Weekly quota near the threshold — pace the long jobs",
    "NotifyWeeklyBody3": "{0}% of the weekly quota is gone",
    "NotifyBurnSuffix": "\nAt the current burn rate, ~{0} to empty",
    "HiddenTitle": "Hidden to tray",
    "HiddenBody": "Quota monitoring keeps running in the background. Click the tray icon to bring the card back; right-click it to quit.",
    "ErrLogAt": "Full log: {0}",
    "WinTitle": "BrainFuel Settings",
    "SettingsTitle": "GLM Coding Plan Monitor",
    "SettingsDesc": "GLM Coding Plan quota, desktop behavior, notifications and software updates",
    "SectionHotkey": "Global hotkey",
    "ChkHotkey": "Enable a show/hide-card hotkey",
    "HotkeyHint": "e.g. Ctrl+Alt+B (letter / digit / F1-F24, with at least one modifier)",
    "HotkeyInvalid": "Invalid hotkey format — previous setting kept",
    "DiagnosticsTitle": "Problem reporting",
    "DiagnosticsHint": "When something breaks, copy the diagnostics (version, account setup, failure log; no keys, no quota data) and paste them to the developer for a fast diagnosis.",
    "DiagnosticsCopy": "Copy diagnostics →",
    "DiagnosticsCopied": "Copied to the clipboard — paste it to the developer.",
    "DiagnosticsCopyFailed": "Copy failed — please screenshot this page instead.",
    "TabGeneral": "General",
    "TabAccount": "Account",
    "TabNotifications": "Notifications",
    "TabSoftware": "Software",
    "SectionAppearance": "Appearance",
    "SectionDesktopBehavior": "Desktop behavior",
    "SectionQuotaDisplay": "Quota display",
    "SectionStartup": "Startup",
    "SectionAccount": "GLM account",
    "AccountDesc": "Your key is used only to query Coding Plan quota from the selected GLM platform. BrainFuel prefers OS-protected secret storage instead of writing the key in plaintext settings.",
    "CredentialSecurityTitle": "API key security",
    "CredentialProtected": "Your API key is protected by {0}; settings.json no longer contains the plaintext key.",
    "CredentialUnavailable": "Your saved API key remains protected by {0}, but the system secret store is temporarily unavailable. BrainFuel will not downgrade it to plaintext and will retry on later quota refreshes.",
    "CredentialFallback": "OS secret storage is currently unavailable. The key is temporarily stored in settings.json with user-only file permissions. Enable the system keyring and save again when possible.",
    "CredentialEmpty": "When you save a key BrainFuel will prefer {0}; it falls back to a user-restricted local settings file only if the system secret store is unavailable.",
    "CredentialForget": "Forget saved API key",
    "CredentialPendingClear": "Saving will remove BrainFuel's stored API key. Even if the system secret store is unavailable now, the old key will not be restored later.",
    "SectionNotifications": "Quota alerts",
    "NotificationsDesc": "Show a local desktop notification when quota is nearly exhausted.",
    "SoftwareDesc": "Manage the BrainFuel application version here. This is separate from refreshing quota data.",
    "SoftwareTrustTitle": "Open-source release trust",
    "SoftwareTrustDesc": "Official builds come from GitHub Actions and Releases include SHA256SUMS plus Artifact Attestation. Windows commercial code signing is not purchased, so SmartScreen may still appear.",
    "FirstRunTitle": "Quick start",
    "FirstRunBody": "Paste your GLM Coding Plan key and save. The main card's “Refresh quota” action only refreshes quota data; Settings, software updates, display movement and About live in the top-right “⋯” app menu.",
    "KeyHint": "Your GLM Coding Plan key (same one the glm-plan-usage plugin uses)",
    "KeyOpenConsole": "Open console to get one →",
    "ValidateTesting": "Testing…",
    "ValidateSaveAnyway": "Save & apply anyway",
    "ValidateBadKey": "Key check failed (HTTP {0}) — verify the key and platform match",
    "ValidateNetwork": "Connection failed — check your network, or save now and it retries later",
    "NotConfigured": "Not configured — click Settings",
    "CredentialUnavailableCard": "System credential temporarily unavailable",
    "LblLanguage": "Language",
    "LblTheme": "Theme",
    "ThemeSystem": "System",
    "ThemeLight": "Light",
    "ThemeDark": "Dark",
    "LblOpacity": "Card opacity",
    "LblRingPalette": "Ring colors",
    "PaletteHint": "Click to preview instantly; saved on Save. The amber/red urgency colors stay fixed.",
    "ChkAlwaysOnTop": "Keep the card above other windows",
    "AlwaysOnTopHint": "When enabled the card stays above other apps. Disable it to let active windows cover BrainFuel and reduce interruption while you work.",
    "PlacementHint": "BrainFuel remembers the display and relative card position. If an external display is unplugged, the card moves to the primary display and will not jump back when the display reconnects. Resolution, DPI and taskbar changes are also clamped to keep the full card visible.",
    "LblApiKey": "API Key",
    "KeyPlaceholder": "Paste your GLM Coding Plan key",
    "LblPlatform": "Platform",
    "PlatformCn": "Zhipu (China) · open.bigmodel.cn",
    "PlatformIntl": "Z.ai (intl) · api.z.ai",
    "PlatformCodex": "Codex · local login",
    "PlatformClaude": "Claude · local login",
    "CliLoginHint": "Codex/Claude accounts need no key: BrainFuel reads the local CLI login (~/.codex, ~/.claude) fresh on every refresh.",
    "CliLoginMissing": "No local {0} login detected — the account cannot be saved.",
    "LblInterval": "Auto-refresh interval",
    "UnitMinutes": "minutes",
    "IntervalInputHint": "Type 1–60, press Enter or click elsewhere, or use a preset.",
    "IntervalActiveStatus": "✓ Active: refresh quota every {0} minutes",
    "IntervalPendingStatus": "Pending: refresh quota every {0} minutes. Click “Save & apply” to activate it.",
    "ChkWeeklyRemaining": "Show weekly as 'remaining' instead of 'used'",
    "ChkHourlyRemaining": "Show 5-hour quota as 'remaining' instead of 'used'",
    "ChkAutostart": "Start BrainFuel on login",
    "ChkNotify": "Notify when quota is nearly exhausted",
    "LblThreshold": "Threshold (used %)",
    "BtnCancel": "Cancel",
    "BtnOK": "OK",
    "BtnSave": "Save & apply",
    "UpdateSectionTitle": "BrainFuel software update",
    "UpdateCurrentVersion": "Current version: v{0}",
    "UpdateInstalledBuild": "Windows installed build",
    "UpdatePortableBuild": "Portable build",
    "BtnCheckUpdates": "Check software updates",
    "UpdateChecking": "Checking for software updates…",
    "UpdateDownloading": "Downloading software update…",
    "UpdateDownloadPercent": "Downloading software update… {0}%",
    "UpdateDownloaded": "Update downloaded",
    "UpdateRestarting": "Installing and restarting BrainFuel…",
    "UpdateAvailableTitle": "Update available",
    "UpdateAvailableBody": "Version {0} is available. Update and restart now?",
    "UpdateRestart": "Update and restart",
    "UpdateQuitAndInstall": "Quit and install",
    "UpdateReadyBody": "The new version is ready — BrainFuel will restart to install it.",
    "UpdateUpToDate": "BrainFuel is up to date",
    "UpdateCheckFailed": "Update check failed: {0}",
    "UpdateInstallFailed": "Installing the update failed: {0}. Your current version is unaffected.",
    "UpdateNotInstalled": "This is a development copy — auto-update is unavailable.",
    "UpdateMsiInstalled": "This copy was installed via the MSI installer — in-app update isn't available for it. Grab the new installer from the releases page.",
    "UpdateInstalledOnly": "Portable builds do not self-update: download the new archive from Releases and extract it over the current folder.",
    "UpdatePortableHint": "Portable builds update by extracting a new archive from Releases over the current folder; in-app updates ship alongside each release.",
    "UpdateOpenDownloads": "View Releases and downloads →",
    "UpdateOpenReleases": "Open releases page",
    "UpdateInstallHint": "To install, extract the downloaded archive over your current BrainFuel folder.",
    "UpdateOpenFolder": "Open Folder",
    "UpdateFailed": "Software update check failed. Please try again later.",
    "UpdateCheckingShort": "Checking…",
    "UpdateDownloadingShort": "Downloading…",
    "UpdateRestartingShort": "Installing…",
    "UpdateUpToDateShort": "Up to date",
    "UpdatePortableShort": "Portable",
    "UpdateFailedShort": "Update failed",
    "JustNow": "just now",
    "MinutesAgo": "{0} min ago",
    "HoursAgo": "{0} h ago",
    "DaysAgo": "{0} d ago",
    "Refreshing": "Refreshing quota…",
    "RefreshFailed": "Quota refresh failed",
    "RefreshFailedAt": "Failed · last {0}",
    "MinutesLater": "in {0} min",
    "HoursLater": "in {0} h",
    "DaysLater": "in {0} d",
    "ResettingSoon": "resetting soon",
    "None": "—",
    "NotifyHourlyTitle": "5-hour quota nearly exhausted",
    "NotifyWeeklyTitle": "Weekly quota nearly exhausted",
    "NotifyUsed": "{0}% used",
    "FailureAuthentication": "API key or platform doesn't match",
    "FailureNetwork": "Network connection failed",
    "FailureTls": "TLS / certificate connection failed",
    "FailureProxy": "Proxy connection failed",
    "FailureTimeout": "Connection timed out",
    "FailureRateLimited": "Rate limited — try again later",
    "FailureNoCodingPlan": "No Coding Plan on this account",
    "FailureServiceUnavailable": "GLM service temporarily unavailable",
    "FailureInvalidResponse": "GLM returned unrecognized data",
    "FailureUnknown": "Quota refresh failed",
    "ValidationAuthentication": "The API key is invalid or does not match the selected platform. Check the key and the Zhipu China / Z.ai international selection.",
    "ValidationNetwork": "BrainFuel cannot reach the GLM service. Check the network and retry, or save now and let BrainFuel refresh when connectivity returns.",
    "ValidationTls": "TLS / certificate negotiation failed. Check the system clock, certificate store, or whether a corporate network is intercepting HTTPS.",
    "ValidationProxy": "Proxy connection failed. Check the system, corporate proxy, or VPN configuration.",
    "ValidationTimeout": "The GLM request timed out. Check the network or proxy and try again later.",
    "ValidationRateLimited": "GLM rate-limited the request. Try again later; you can save the current settings now.",
    "ValidationNoCodingPlan": "No usable Coding Plan quota was found for this account. Confirm the key belongs to an account with GLM Coding Plan enabled; for recently purchased plans the monitor endpoint may not cover them yet — you can save and keep refreshing.",
    "ValidationServiceUnavailable": "The GLM service is temporarily unavailable. Try again later; you can save the current settings now.",
    "ValidationInvalidResponse": "GLM returned data BrainFuel does not recognize, possibly due to a temporary API change. You can save now and retry later.",
    "ValidationUnknown": "Quota validation failed. You can save the settings and try again later.",
    ]

    /// Look up a key in the active language, falling back to zh then the key
    /// itself. "{0}"-style placeholders are substituted from the args.
    static func t(_ key: String, _ args: String...) -> String {
        let table = language == "en" ? en : zh
        var s = table[key] ?? zh[key] ?? key
        for (i, arg) in args.enumerated() {
            s = s.replacingOccurrences(of: "{\(i)}", with: arg)
        }
        return s
    }
}
