using System.Collections.Generic;
using Avalonia;

namespace BrainFuel.Services;

public enum AppLanguage { Zh, En }

public static class Strings
{
    public static AppLanguage Current { get; private set; } = AppLanguage.Zh;

    private static readonly Dictionary<AppLanguage, Dictionary<string, string>> Tables = new()
    {
        [AppLanguage.Zh] = new()
        {
            ["LblHourly"] = "5 小时",
            ["LblWeekly"] = "周用量",
            ["CardSubtitle"] = "GLM Coding Plan 额度",
            ["QuotaDataStatus"] = "额度数据",
            ["BtnRefreshQuota"] = "刷新额度",
            ["MenuMoreTip"] = "应用菜单",
            ["MenuRefresh"] = "刷新额度",
            ["MenuSettings"] = "设置…",
            ["MenuCheckUpdates"] = "检查软件更新…",
            ["MenuQuit"] = "退出",
            ["MenuHide"] = "隐藏到托盘",
            ["TrayShow"] = "显示卡片",
            ["TraySettings"] = "设置…",
            ["TrayQuit"] = "退出",
            ["TrayTooltip"] = "BrainFuel · GLM 额度监控",
            ["WinTitle"] = "BrainFuel 设置",
            ["SettingsTitle"] = "GLM 套餐额度监控",
            ["SettingsDesc"] = "GLM Coding Plan 额度、外观、通知与软件更新",
            ["TabGeneral"] = "常规",
            ["TabAccount"] = "账户",
            ["TabNotifications"] = "通知",
            ["TabSoftware"] = "软件",
            ["SectionAppearance"] = "外观",
            ["SectionQuotaDisplay"] = "额度显示",
            ["SectionStartup"] = "启动",
            ["SectionAccount"] = "GLM 账户",
            ["AccountDesc"] = "Key 仅用于向你选择的 GLM 平台查询 Coding Plan 额度。",
            ["SectionNotifications"] = "额度提醒",
            ["NotificationsDesc"] = "当额度接近耗尽时显示本地桌面通知。",
            ["SoftwareDesc"] = "这里管理 BrainFuel 自身版本；与“刷新额度”完全独立。",
            ["SoftwareTrustTitle"] = "开源与发布可信度",
            ["SoftwareTrustDesc"] = "正式版本由 GitHub Actions 构建，Release 提供 SHA256SUMS 与 Artifact Attestation。Windows 未购买商业代码签名，因此仍可能出现 SmartScreen 提示。",
            ["FirstRunTitle"] = "快速上手",
            ["FirstRunBody"] = "粘贴 GLM Coding Plan Key 并保存后，主卡片会开始显示额度。主卡片底部的“刷新额度”只刷新额度数据；设置、软件更新与关于位于右上角“⋯”应用菜单。",
            ["KeyHint"] = "GLM Coding Plan 专用 Key，与 glm-plan-usage 插件同款",
            ["KeyOpenConsole"] = "打开控制台获取 →",
            ["ValidateTesting"] = "验证中…",
            ["ValidateSaveAnyway"] = "仍然保存并应用",
            ["ValidateBadKey"] = "Key 验证失败（HTTP {0}）— 请检查 Key 与平台是否匹配",
            ["ValidateNetwork"] = "连接失败 — 请检查网络；也可先保存，联网后自动刷新",
            ["NotConfigured"] = "未配置，点击设置",
            ["LblLanguage"] = "语言",
            ["LblTheme"] = "主题",
            ["ThemeSystem"] = "跟随系统",
            ["ThemeLight"] = "亮色",
            ["ThemeDark"] = "暗色",
            ["LblOpacity"] = "卡片透明度",
            ["LblApiKey"] = "API Key",
            ["KeyPlaceholder"] = "粘贴 GLM Coding Plan Key",
            ["LblPlatform"] = "平台",
            ["PlatformCn"] = "智谱国内 · open.bigmodel.cn",
            ["PlatformIntl"] = "Z.ai 国际 · api.z.ai",
            ["LblInterval"] = "自动刷新间隔",
            ["UnitMinutes"] = "分钟",
            ["IntervalInputHint"] = "可直接输入 1–60；输入后按 Enter 或点击空白处确认，也可使用快捷值。",
            ["IntervalActiveStatus"] = "✓ 当前生效：每 {0} 分钟刷新额度",
            ["IntervalPendingStatus"] = "待保存：每 {0} 分钟刷新额度。点击“保存并应用”后生效。",
            ["ChkWeeklyRemaining"] = "周用量显示「剩余」而非「已用」",
            ["ChkHourlyRemaining"] = "5 小时显示「剩余」而非「已用」",
            ["ChkAutostart"] = "开机自动启动 BrainFuel",
            ["ChkNotify"] = "额度接近耗尽时桌面通知",
            ["LblThreshold"] = "触发阈值（已用 %）",
            ["BtnCancel"] = "取消",
            ["BtnSave"] = "保存并应用",
            ["UpdateSectionTitle"] = "BrainFuel 软件更新",
            ["UpdateCurrentVersion"] = "当前版本：v{0}",
            ["UpdateInstalledBuild"] = "Windows 安装版",
            ["UpdatePortableBuild"] = "便携版",
            ["BtnCheckUpdates"] = "检查软件更新",
            ["UpdateChecking"] = "正在检查软件更新…",
            ["UpdateDownloading"] = "正在下载软件更新…",
            ["UpdateRestarting"] = "正在安装并重启 BrainFuel…",
            ["UpdateUpToDate"] = "BrainFuel 已是最新版本",
            ["UpdateInstalledOnly"] = "便携版不会自更新，请从 Releases 手动下载最新版 ZIP",
            ["UpdatePortableHint"] = "便携版采用手动更新；Windows 安装版支持自动增量更新。",
            ["UpdateOpenDownloads"] = "查看 Releases 与下载 →",
            ["UpdateFailed"] = "软件更新检查失败，请稍后重试",
            ["UpdateCheckingShort"] = "检查中…",
            ["UpdateDownloadingShort"] = "下载中…",
            ["UpdateRestartingShort"] = "安装中…",
            ["UpdateUpToDateShort"] = "已是最新",
            ["UpdatePortableShort"] = "便携版",
            ["UpdateFailedShort"] = "更新失败",
            ["JustNow"] = "刚刚",
            ["MinutesAgo"] = "{0} 分钟前",
            ["HoursAgo"] = "{0} 小时前",
            ["DaysAgo"] = "{0} 天前",
            ["Refreshing"] = "正在刷新额度…",
            ["RefreshFailed"] = "额度刷新失败",
            ["RefreshFailedAt"] = "刷新失败 · 上次 {0}",
            ["MinutesLater"] = "{0} 分钟后",
            ["HoursLater"] = "{0} 小时后",
            ["DaysLater"] = "{0} 天后",
            ["ResettingSoon"] = "即将重置",
            ["None"] = "—",
            ["NotifyHourlyTitle"] = "5 小时额度即将耗尽",
            ["NotifyWeeklyTitle"] = "周额度即将耗尽",
            ["NotifyUsed"] = "已用 {0}%",
        },
        [AppLanguage.En] = new()
        {
            ["LblHourly"] = "5 hours",
            ["LblWeekly"] = "Weekly",
            ["CardSubtitle"] = "GLM Coding Plan quota",
            ["QuotaDataStatus"] = "Quota data",
            ["BtnRefreshQuota"] = "Refresh quota",
            ["MenuMoreTip"] = "App menu",
            ["MenuRefresh"] = "Refresh quota",
            ["MenuSettings"] = "Settings…",
            ["MenuCheckUpdates"] = "Check software updates…",
            ["MenuQuit"] = "Quit",
            ["MenuHide"] = "Hide to tray",
            ["TrayShow"] = "Show widget",
            ["TraySettings"] = "Settings…",
            ["TrayQuit"] = "Quit",
            ["TrayTooltip"] = "BrainFuel · GLM quota monitor",
            ["WinTitle"] = "BrainFuel Settings",
            ["SettingsTitle"] = "GLM Coding Plan Monitor",
            ["SettingsDesc"] = "GLM Coding Plan quota, appearance, notifications and software updates",
            ["TabGeneral"] = "General",
            ["TabAccount"] = "Account",
            ["TabNotifications"] = "Notifications",
            ["TabSoftware"] = "Software",
            ["SectionAppearance"] = "Appearance",
            ["SectionQuotaDisplay"] = "Quota display",
            ["SectionStartup"] = "Startup",
            ["SectionAccount"] = "GLM account",
            ["AccountDesc"] = "Your key is used only to query Coding Plan quota from the GLM platform you select.",
            ["SectionNotifications"] = "Quota alerts",
            ["NotificationsDesc"] = "Show a local desktop notification when quota is nearly exhausted.",
            ["SoftwareDesc"] = "Manage the BrainFuel application version here. This is separate from refreshing quota data.",
            ["SoftwareTrustTitle"] = "Open-source release trust",
            ["SoftwareTrustDesc"] = "Official builds come from GitHub Actions and Releases include SHA256SUMS plus Artifact Attestation. Windows commercial code signing is not purchased, so SmartScreen may still appear.",
            ["FirstRunTitle"] = "Quick start",
            ["FirstRunBody"] = "Paste your GLM Coding Plan key and save. The main card's “Refresh quota” action only refreshes quota data; Settings, software updates and About live in the top-right “⋯” app menu.",
            ["KeyHint"] = "Your GLM Coding Plan key (same one the glm-plan-usage plugin uses)",
            ["KeyOpenConsole"] = "Open console to get one →",
            ["ValidateTesting"] = "Testing…",
            ["ValidateSaveAnyway"] = "Save & apply anyway",
            ["ValidateBadKey"] = "Key check failed (HTTP {0}) — verify the key and platform match",
            ["ValidateNetwork"] = "Connection failed — check your network, or save now and it retries later",
            ["NotConfigured"] = "Not configured — click Settings",
            ["LblLanguage"] = "Language",
            ["LblTheme"] = "Theme",
            ["ThemeSystem"] = "System",
            ["ThemeLight"] = "Light",
            ["ThemeDark"] = "Dark",
            ["LblOpacity"] = "Card opacity",
            ["LblApiKey"] = "API Key",
            ["KeyPlaceholder"] = "Paste your GLM Coding Plan key",
            ["LblPlatform"] = "Platform",
            ["PlatformCn"] = "Zhipu (China) · open.bigmodel.cn",
            ["PlatformIntl"] = "Z.ai (intl) · api.z.ai",
            ["LblInterval"] = "Auto-refresh interval",
            ["UnitMinutes"] = "minutes",
            ["IntervalInputHint"] = "Type 1–60, press Enter or click elsewhere, or use a preset.",
            ["IntervalActiveStatus"] = "✓ Active: refresh quota every {0} minutes",
            ["IntervalPendingStatus"] = "Pending: refresh quota every {0} minutes. Click “Save & apply” to activate it.",
            ["ChkWeeklyRemaining"] = "Show weekly as 'remaining' instead of 'used'",
            ["ChkHourlyRemaining"] = "Show 5-hour quota as 'remaining' instead of 'used'",
            ["ChkAutostart"] = "Start BrainFuel on login",
            ["ChkNotify"] = "Notify when quota is nearly exhausted",
            ["LblThreshold"] = "Threshold (used %)",
            ["BtnCancel"] = "Cancel",
            ["BtnSave"] = "Save & apply",
            ["UpdateSectionTitle"] = "BrainFuel software update",
            ["UpdateCurrentVersion"] = "Current version: v{0}",
            ["UpdateInstalledBuild"] = "Windows installed build",
            ["UpdatePortableBuild"] = "Portable build",
            ["BtnCheckUpdates"] = "Check software updates",
            ["UpdateChecking"] = "Checking for software updates…",
            ["UpdateDownloading"] = "Downloading software update…",
            ["UpdateRestarting"] = "Installing and restarting BrainFuel…",
            ["UpdateUpToDate"] = "BrainFuel is up to date",
            ["UpdateInstalledOnly"] = "Portable builds do not self-update. Download the latest ZIP from Releases.",
            ["UpdatePortableHint"] = "Portable builds update manually; the Windows installed build supports automatic delta updates.",
            ["UpdateOpenDownloads"] = "View Releases and downloads →",
            ["UpdateFailed"] = "Software update check failed. Please try again later.",
            ["UpdateCheckingShort"] = "Checking…",
            ["UpdateDownloadingShort"] = "Downloading…",
            ["UpdateRestartingShort"] = "Installing…",
            ["UpdateUpToDateShort"] = "Up to date",
            ["UpdatePortableShort"] = "Portable",
            ["UpdateFailedShort"] = "Update failed",
            ["JustNow"] = "just now",
            ["MinutesAgo"] = "{0} min ago",
            ["HoursAgo"] = "{0} h ago",
            ["DaysAgo"] = "{0} d ago",
            ["Refreshing"] = "Refreshing quota…",
            ["RefreshFailed"] = "Quota refresh failed",
            ["RefreshFailedAt"] = "Failed · last {0}",
            ["MinutesLater"] = "in {0} min",
            ["HoursLater"] = "in {0} h",
            ["DaysLater"] = "in {0} d",
            ["ResettingSoon"] = "resetting soon",
            ["None"] = "—",
            ["NotifyHourlyTitle"] = "5-hour quota nearly exhausted",
            ["NotifyWeeklyTitle"] = "Weekly quota nearly exhausted",
            ["NotifyUsed"] = "{0}% used",
        },
    };

    public static string Get(string key, params object[] args)
    {
        var s = Tables[Current].TryGetValue(key, out var v) ? v : key;
        return args.Length == 0 ? s : string.Format(s, args);
    }

    public static void ApplyLanguage(AppLanguage lang)
    {
        Current = lang;
        if (Application.Current is null) return;
        var res = Application.Current.Resources;
        foreach (var kv in Tables[lang])
            res[kv.Key] = kv.Value;
    }
}
