// Generated by Rivet. Do not edit by hand.
#pragma once

#include <cstdint>
#include <exception>
#include <functional>
#include <future>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <variant>
#include <vector>

#include "backend.hpp"

namespace rivet_app {
inline constexpr char kModuleName[] = "backend";
inline constexpr char kEntryName[] = "start";
inline constexpr char kDisplayName[] = "BrainFuel";
inline constexpr char kVersion[] = "0.9.0";
inline constexpr std::int64_t kBuild = 1;
inline constexpr char kIdentifier[] = "site.jrtx.brainfuel";
inline constexpr char kReleaseChannel[] = "stable";

enum class FailureKind { authentication, network, tls, proxy, timeout, rate_limited, no_coding_plan, service_unavailable, invalid_response, unknown };

enum class Provider { glm, codex, claude };

enum class Severity { calm, amber, red };

struct Account {
  std::string id;
  std::string name;
  Provider provider;
  std::string base_domain;
  bool configured;
};

struct AccountDraft {
  std::optional<std::string> id;
  std::string name;
  Provider provider;
  std::string base_domain;
  std::optional<std::string> api_key;
  bool clear_key;
};

struct Alert {
  std::string account_id;
  std::string which;
  std::string message;
};

struct BurnInfo {
  std::optional<std::int64_t> rate_bp_per_hour;
  std::optional<std::int64_t> minutes_to_empty;
  std::optional<std::string> comparison;
};

struct WindowUsage {
  std::optional<std::int64_t> used_bp;
  std::optional<std::int64_t> reset_at_ms;
};

struct HistorySample {
  std::int64_t at_ms;
  std::optional<std::int64_t> hourly_bp;
  std::optional<std::int64_t> weekly_bp;
};

struct Details {
  WindowUsage hourly;
  WindowUsage weekly;
  BurnInfo hourly_burn;
  BurnInfo weekly_burn;
  std::vector<HistorySample> history;
  std::string history_note;
};

struct FailureInfo {
  FailureKind kind;
  std::string message;
};

struct QuotaSnapshot {
  std::string account_id;
  std::string plan_level;
  WindowUsage hourly;
  WindowUsage weekly;
  Severity severity;
  std::int64_t fetched_at_ms;
  std::optional<FailureInfo> failure;
};

struct SettingsData {
  std::int64_t refresh_interval_minutes;
  bool hourly_remaining;
  bool weekly_remaining;
  bool notify_enabled;
  std::int64_t notify_threshold;
  std::string theme;
  std::string language;
  std::string size_mode;
  bool always_on_top;
  bool autostart;
  bool hotkey_enabled;
  std::string hotkey_combo;
  std::string ring_palette;
  std::int64_t card_opacity_bp;
  std::string credential_state;
};

template <typename T>
struct Result {
  std::optional<T> value;
  std::exception_ptr error;
  bool succeeded() const noexcept { return value.has_value() && !error; }
  T const& get() const { if (error) std::rethrow_exception(error); if (!value) throw std::runtime_error("Rivet async result has no value"); return *value; }
};

template <>
struct Result<void> {
  std::exception_ptr error;
  bool succeeded() const noexcept { return !error; }
  void get() const { if (error) std::rethrow_exception(error); }
};

namespace detail {
inline rivet::Value encode_String(std::string const& v) { return rivet::Value(v); }
inline rivet::Value encode_Int64(std::int64_t v) { return rivet::Value(v); }
inline rivet::Value encode__Optional_Int64_(std::optional<std::int64_t> const& v) { return v ? encode_Int64(*v) : rivet::Value{}; }
inline rivet::Value encode_WindowUsage(WindowUsage const& v) { rivet::Value::List r; r.reserve(2); r.push_back(encode__Optional_Int64_(v.used_bp)); r.push_back(encode__Optional_Int64_(v.reset_at_ms)); return rivet::Value(std::move(r)); }
inline rivet::Value encode__Optional_String_(std::optional<std::string> const& v) { return v ? encode_String(*v) : rivet::Value{}; }
inline rivet::Value encode_BurnInfo(BurnInfo const& v) { rivet::Value::List r; r.reserve(3); r.push_back(encode__Optional_Int64_(v.rate_bp_per_hour)); r.push_back(encode__Optional_Int64_(v.minutes_to_empty)); r.push_back(encode__Optional_String_(v.comparison)); return rivet::Value(std::move(r)); }
inline rivet::Value encode_HistorySample(HistorySample const& v) { rivet::Value::List r; r.reserve(3); r.push_back(encode_Int64(v.at_ms)); r.push_back(encode__Optional_Int64_(v.hourly_bp)); r.push_back(encode__Optional_Int64_(v.weekly_bp)); return rivet::Value(std::move(r)); }
inline rivet::Value encode__List_HistorySample_(std::vector<HistorySample> const& xs) { rivet::Value::List r; r.reserve(xs.size()); for (auto const& x : xs) r.push_back(encode_HistorySample(x)); return rivet::Value(std::move(r)); }
inline rivet::Value encode_Details(Details const& v) { rivet::Value::List r; r.reserve(6); r.push_back(encode_WindowUsage(v.hourly)); r.push_back(encode_WindowUsage(v.weekly)); r.push_back(encode_BurnInfo(v.hourly_burn)); r.push_back(encode_BurnInfo(v.weekly_burn)); r.push_back(encode__List_HistorySample_(v.history)); r.push_back(encode_String(v.history_note)); return rivet::Value(std::move(r)); }
inline rivet::Value encode_Bool(bool v) { return rivet::Value(v); }
inline rivet::Value encode_SettingsData(SettingsData const& v) { rivet::Value::List r; r.reserve(15); r.push_back(encode_Int64(v.refresh_interval_minutes)); r.push_back(encode_Bool(v.hourly_remaining)); r.push_back(encode_Bool(v.weekly_remaining)); r.push_back(encode_Bool(v.notify_enabled)); r.push_back(encode_Int64(v.notify_threshold)); r.push_back(encode_String(v.theme)); r.push_back(encode_String(v.language)); r.push_back(encode_String(v.size_mode)); r.push_back(encode_Bool(v.always_on_top)); r.push_back(encode_Bool(v.autostart)); r.push_back(encode_Bool(v.hotkey_enabled)); r.push_back(encode_String(v.hotkey_combo)); r.push_back(encode_String(v.ring_palette)); r.push_back(encode_Int64(v.card_opacity_bp)); r.push_back(encode_String(v.credential_state)); return rivet::Value(std::move(r)); }
inline rivet::Value encode_Void() { return rivet::Value{}; }
inline rivet::Value encode_Provider(Provider v) { switch (v) { case Provider::glm: return rivet::Value(std::string("glm")); case Provider::codex: return rivet::Value(std::string("codex")); case Provider::claude: return rivet::Value(std::string("claude")); } throw std::runtime_error("invalid Rivet enum value"); }
inline rivet::Value encode_Account(Account const& v) { rivet::Value::List r; r.reserve(5); r.push_back(encode_String(v.id)); r.push_back(encode_String(v.name)); r.push_back(encode_Provider(v.provider)); r.push_back(encode_String(v.base_domain)); r.push_back(encode_Bool(v.configured)); return rivet::Value(std::move(r)); }
inline rivet::Value encode__List_Account_(std::vector<Account> const& xs) { rivet::Value::List r; r.reserve(xs.size()); for (auto const& x : xs) r.push_back(encode_Account(x)); return rivet::Value(std::move(r)); }
inline rivet::Value encode_AccountDraft(AccountDraft const& v) { rivet::Value::List r; r.reserve(6); r.push_back(encode__Optional_String_(v.id)); r.push_back(encode_String(v.name)); r.push_back(encode_Provider(v.provider)); r.push_back(encode_String(v.base_domain)); r.push_back(encode__Optional_String_(v.api_key)); r.push_back(encode_Bool(v.clear_key)); return rivet::Value(std::move(r)); }
inline rivet::Value encode_Alert(Alert const& v) { rivet::Value::List r; r.reserve(3); r.push_back(encode_String(v.account_id)); r.push_back(encode_String(v.which)); r.push_back(encode_String(v.message)); return rivet::Value(std::move(r)); }
inline rivet::Value encode_Severity(Severity v) { switch (v) { case Severity::calm: return rivet::Value(std::string("calm")); case Severity::amber: return rivet::Value(std::string("amber")); case Severity::red: return rivet::Value(std::string("red")); } throw std::runtime_error("invalid Rivet enum value"); }
inline rivet::Value encode_FailureKind(FailureKind v) { switch (v) { case FailureKind::authentication: return rivet::Value(std::string("authentication")); case FailureKind::network: return rivet::Value(std::string("network")); case FailureKind::tls: return rivet::Value(std::string("tls")); case FailureKind::proxy: return rivet::Value(std::string("proxy")); case FailureKind::timeout: return rivet::Value(std::string("timeout")); case FailureKind::rate_limited: return rivet::Value(std::string("rate-limited")); case FailureKind::no_coding_plan: return rivet::Value(std::string("no-coding-plan")); case FailureKind::service_unavailable: return rivet::Value(std::string("service-unavailable")); case FailureKind::invalid_response: return rivet::Value(std::string("invalid-response")); case FailureKind::unknown: return rivet::Value(std::string("unknown")); } throw std::runtime_error("invalid Rivet enum value"); }
inline rivet::Value encode_FailureInfo(FailureInfo const& v) { rivet::Value::List r; r.reserve(2); r.push_back(encode_FailureKind(v.kind)); r.push_back(encode_String(v.message)); return rivet::Value(std::move(r)); }
inline rivet::Value encode__Optional_FailureInfo_(std::optional<FailureInfo> const& v) { return v ? encode_FailureInfo(*v) : rivet::Value{}; }
inline rivet::Value encode_QuotaSnapshot(QuotaSnapshot const& v) { rivet::Value::List r; r.reserve(7); r.push_back(encode_String(v.account_id)); r.push_back(encode_String(v.plan_level)); r.push_back(encode_WindowUsage(v.hourly)); r.push_back(encode_WindowUsage(v.weekly)); r.push_back(encode_Severity(v.severity)); r.push_back(encode_Int64(v.fetched_at_ms)); r.push_back(encode__Optional_FailureInfo_(v.failure)); return rivet::Value(std::move(r)); }
inline rivet::Value encode__Optional_QuotaSnapshot_(std::optional<QuotaSnapshot> const& v) { return v ? encode_QuotaSnapshot(*v) : rivet::Value{}; }

inline std::string decode_String(rivet::Value const& v) { if (auto p = std::get_if<std::string>(&v.data)) return *p; throw std::runtime_error("Rivet result type mismatch: String"); }
inline std::int64_t decode_Int64(rivet::Value const& v) { if (auto p = std::get_if<std::int64_t>(&v.data)) return *p; throw std::runtime_error("Rivet result type mismatch: Int64"); }
inline std::optional<std::int64_t> decode__Optional_Int64_(rivet::Value const& v) { if (std::holds_alternative<std::monostate>(v.data)) return std::nullopt; return decode_Int64(v); }
inline WindowUsage decode_WindowUsage(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p || p->size() != 2) throw std::runtime_error("Rivet result type mismatch: WindowUsage"); return WindowUsage{decode__Optional_Int64_((*p)[0]), decode__Optional_Int64_((*p)[1])}; }
inline std::optional<std::string> decode__Optional_String_(rivet::Value const& v) { if (std::holds_alternative<std::monostate>(v.data)) return std::nullopt; return decode_String(v); }
inline BurnInfo decode_BurnInfo(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p || p->size() != 3) throw std::runtime_error("Rivet result type mismatch: BurnInfo"); return BurnInfo{decode__Optional_Int64_((*p)[0]), decode__Optional_Int64_((*p)[1]), decode__Optional_String_((*p)[2])}; }
inline HistorySample decode_HistorySample(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p || p->size() != 3) throw std::runtime_error("Rivet result type mismatch: HistorySample"); return HistorySample{decode_Int64((*p)[0]), decode__Optional_Int64_((*p)[1]), decode__Optional_Int64_((*p)[2])}; }
inline std::vector<HistorySample> decode__List_HistorySample_(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p) throw std::runtime_error("Rivet result type mismatch: (List HistorySample)"); std::vector<HistorySample> r; r.reserve(p->size()); for (auto const& x : *p) r.push_back(decode_HistorySample(x)); return r; }
inline Details decode_Details(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p || p->size() != 6) throw std::runtime_error("Rivet result type mismatch: Details"); return Details{decode_WindowUsage((*p)[0]), decode_WindowUsage((*p)[1]), decode_BurnInfo((*p)[2]), decode_BurnInfo((*p)[3]), decode__List_HistorySample_((*p)[4]), decode_String((*p)[5])}; }
inline bool decode_Bool(rivet::Value const& v) { if (auto p = std::get_if<bool>(&v.data)) return *p; throw std::runtime_error("Rivet result type mismatch: Bool"); }
inline SettingsData decode_SettingsData(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p || p->size() != 15) throw std::runtime_error("Rivet result type mismatch: SettingsData"); return SettingsData{decode_Int64((*p)[0]), decode_Bool((*p)[1]), decode_Bool((*p)[2]), decode_Bool((*p)[3]), decode_Int64((*p)[4]), decode_String((*p)[5]), decode_String((*p)[6]), decode_String((*p)[7]), decode_Bool((*p)[8]), decode_Bool((*p)[9]), decode_Bool((*p)[10]), decode_String((*p)[11]), decode_String((*p)[12]), decode_Int64((*p)[13]), decode_String((*p)[14])}; }
inline void decode_Void(rivet::Value const& v) { if (!std::holds_alternative<std::monostate>(v.data)) throw std::runtime_error("Rivet result type mismatch: Void"); }
inline Provider decode_Provider(rivet::Value const& v) { auto p = std::get_if<std::string>(&v.data); if (p) { if (*p == "glm") return Provider::glm; if (*p == "codex") return Provider::codex; if (*p == "claude") return Provider::claude; } throw std::runtime_error("Rivet result type mismatch: Provider"); }
inline Account decode_Account(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p || p->size() != 5) throw std::runtime_error("Rivet result type mismatch: Account"); return Account{decode_String((*p)[0]), decode_String((*p)[1]), decode_Provider((*p)[2]), decode_String((*p)[3]), decode_Bool((*p)[4])}; }
inline std::vector<Account> decode__List_Account_(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p) throw std::runtime_error("Rivet result type mismatch: (List Account)"); std::vector<Account> r; r.reserve(p->size()); for (auto const& x : *p) r.push_back(decode_Account(x)); return r; }
inline AccountDraft decode_AccountDraft(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p || p->size() != 6) throw std::runtime_error("Rivet result type mismatch: AccountDraft"); return AccountDraft{decode__Optional_String_((*p)[0]), decode_String((*p)[1]), decode_Provider((*p)[2]), decode_String((*p)[3]), decode__Optional_String_((*p)[4]), decode_Bool((*p)[5])}; }
inline Alert decode_Alert(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p || p->size() != 3) throw std::runtime_error("Rivet result type mismatch: Alert"); return Alert{decode_String((*p)[0]), decode_String((*p)[1]), decode_String((*p)[2])}; }
inline Severity decode_Severity(rivet::Value const& v) { auto p = std::get_if<std::string>(&v.data); if (p) { if (*p == "calm") return Severity::calm; if (*p == "amber") return Severity::amber; if (*p == "red") return Severity::red; } throw std::runtime_error("Rivet result type mismatch: Severity"); }
inline FailureKind decode_FailureKind(rivet::Value const& v) { auto p = std::get_if<std::string>(&v.data); if (p) { if (*p == "authentication") return FailureKind::authentication; if (*p == "network") return FailureKind::network; if (*p == "tls") return FailureKind::tls; if (*p == "proxy") return FailureKind::proxy; if (*p == "timeout") return FailureKind::timeout; if (*p == "rate-limited") return FailureKind::rate_limited; if (*p == "no-coding-plan") return FailureKind::no_coding_plan; if (*p == "service-unavailable") return FailureKind::service_unavailable; if (*p == "invalid-response") return FailureKind::invalid_response; if (*p == "unknown") return FailureKind::unknown; } throw std::runtime_error("Rivet result type mismatch: FailureKind"); }
inline FailureInfo decode_FailureInfo(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p || p->size() != 2) throw std::runtime_error("Rivet result type mismatch: FailureInfo"); return FailureInfo{decode_FailureKind((*p)[0]), decode_String((*p)[1])}; }
inline std::optional<FailureInfo> decode__Optional_FailureInfo_(rivet::Value const& v) { if (std::holds_alternative<std::monostate>(v.data)) return std::nullopt; return decode_FailureInfo(v); }
inline QuotaSnapshot decode_QuotaSnapshot(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p || p->size() != 7) throw std::runtime_error("Rivet result type mismatch: QuotaSnapshot"); return QuotaSnapshot{decode_String((*p)[0]), decode_String((*p)[1]), decode_WindowUsage((*p)[2]), decode_WindowUsage((*p)[3]), decode_Severity((*p)[4]), decode_Int64((*p)[5]), decode__Optional_FailureInfo_((*p)[6])}; }
inline std::optional<QuotaSnapshot> decode__Optional_QuotaSnapshot_(rivet::Value const& v) { if (std::holds_alternative<std::monostate>(v.data)) return std::nullopt; return decode_QuotaSnapshot(v); }
}  // namespace detail

struct Alert_triggeredEvent { Alert value; };
struct Quota_updatedEvent { QuotaSnapshot value; };
using Event = std::variant<Alert_triggeredEvent, Quota_updatedEvent>;
inline Event decode_event(std::string const& name, rivet::Value const& value) {
  if (name == "alert-triggered") return Event{Alert_triggeredEvent{detail::decode_Alert(value)}};
  if (name == "quota-updated") return Event{Quota_updatedEvent{detail::decode_QuotaSnapshot(value)}};
  throw std::runtime_error("unknown Rivet event: " + name);
}

class API {
 public:
  explicit API(rivet::linux_runtime::Backend& backend) : backend_(backend) {}

  std::future<Details> get_details(std::string account_id) { auto raw = backend_.call("get-details", rivet::Value::List{detail::encode_String(account_id)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> Details { return detail::decode_Details(raw.get()); }); }
  [[nodiscard]] std::uint64_t get_details_async(std::string account_id, std::function<void(Result<Details>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("get-details", rivet::Value::List{detail::encode_String(account_id)}, [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<Details> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_Details(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<std::string> get_diagnostics() { auto raw = backend_.call("get-diagnostics", rivet::Value::List{}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> std::string { return detail::decode_String(raw.get()); }); }
  [[nodiscard]] std::uint64_t get_diagnostics_async(std::function<void(Result<std::string>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("get-diagnostics", rivet::Value::List{}, [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<std::string> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_String(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<SettingsData> get_settings() { auto raw = backend_.call("get-settings", rivet::Value::List{}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> SettingsData { return detail::decode_SettingsData(raw.get()); }); }
  [[nodiscard]] std::uint64_t get_settings_async(std::function<void(Result<SettingsData>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("get-settings", rivet::Value::List{}, [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<SettingsData> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_SettingsData(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<void> initialize() { auto raw = backend_.call("initialize", rivet::Value::List{}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> void { detail::decode_Void(raw.get()); }); }
  [[nodiscard]] std::uint64_t initialize_async(std::function<void(Result<void>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("initialize", rivet::Value::List{}, [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<void> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); detail::decode_Void(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<void> refresh_now() { auto raw = backend_.call("refresh-now", rivet::Value::List{}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> void { detail::decode_Void(raw.get()); }); }
  [[nodiscard]] std::uint64_t refresh_now_async(std::function<void(Result<void>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("refresh-now", rivet::Value::List{}, [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<void> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); detail::decode_Void(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<std::vector<Account>> remove_account(std::string id) { auto raw = backend_.call("remove-account", rivet::Value::List{detail::encode_String(id)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> std::vector<Account> { return detail::decode__List_Account_(raw.get()); }); }
  [[nodiscard]] std::uint64_t remove_account_async(std::string id, std::function<void(Result<std::vector<Account>>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("remove-account", rivet::Value::List{detail::encode_String(id)}, [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<std::vector<Account>> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode__List_Account_(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<std::vector<Account>> save_account(AccountDraft draft) { auto raw = backend_.call("save-account", rivet::Value::List{detail::encode_AccountDraft(draft)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> std::vector<Account> { return detail::decode__List_Account_(raw.get()); }); }
  [[nodiscard]] std::uint64_t save_account_async(AccountDraft draft, std::function<void(Result<std::vector<Account>>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("save-account", rivet::Value::List{detail::encode_AccountDraft(draft)}, [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<std::vector<Account>> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode__List_Account_(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<SettingsData> save_settings(SettingsData settings) { auto raw = backend_.call("save-settings", rivet::Value::List{detail::encode_SettingsData(settings)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> SettingsData { return detail::decode_SettingsData(raw.get()); }); }
  [[nodiscard]] std::uint64_t save_settings_async(SettingsData settings, std::function<void(Result<SettingsData>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("save-settings", rivet::Value::List{detail::encode_SettingsData(settings)}, [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<SettingsData> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_SettingsData(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<void> switch_account(std::string id) { auto raw = backend_.call("switch-account", rivet::Value::List{detail::encode_String(id)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> void { detail::decode_Void(raw.get()); }); }
  [[nodiscard]] std::uint64_t switch_account_async(std::string id, std::function<void(Result<void>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("switch-account", rivet::Value::List{detail::encode_String(id)}, [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<void> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); detail::decode_Void(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }

  // Shared state
  std::future<std::vector<Account>> get_accounts() { auto raw = backend_.get_state("accounts"); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> std::vector<Account> { return detail::decode__List_Account_(raw.get()); }); }
  [[nodiscard]] std::uint64_t get_accounts_async(std::function<void(Result<std::vector<Account>>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.get_state_async("accounts", [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<std::vector<Account>> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode__List_Account_(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<std::vector<Account>> set_accounts(std::vector<Account> value) { auto raw = backend_.set_state("accounts", detail::encode__List_Account_(value)); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> std::vector<Account> { return detail::decode__List_Account_(raw.get()); }); }
  [[nodiscard]] std::uint64_t set_accounts_async(std::vector<Account> value, std::function<void(Result<std::vector<Account>>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.set_state_async("accounts", detail::encode__List_Account_(value), [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<std::vector<Account>> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode__List_Account_(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<std::string> get_active_account_id() { auto raw = backend_.get_state("active-account-id"); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> std::string { return detail::decode_String(raw.get()); }); }
  [[nodiscard]] std::uint64_t get_active_account_id_async(std::function<void(Result<std::string>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.get_state_async("active-account-id", [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<std::string> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_String(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<std::string> set_active_account_id(std::string value) { auto raw = backend_.set_state("active-account-id", detail::encode_String(value)); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> std::string { return detail::decode_String(raw.get()); }); }
  [[nodiscard]] std::uint64_t set_active_account_id_async(std::string value, std::function<void(Result<std::string>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.set_state_async("active-account-id", detail::encode_String(value), [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<std::string> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_String(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<std::optional<QuotaSnapshot>> get_snapshot() { auto raw = backend_.get_state("snapshot"); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> std::optional<QuotaSnapshot> { return detail::decode__Optional_QuotaSnapshot_(raw.get()); }); }
  [[nodiscard]] std::uint64_t get_snapshot_async(std::function<void(Result<std::optional<QuotaSnapshot>>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.get_state_async("snapshot", [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<std::optional<QuotaSnapshot>> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode__Optional_QuotaSnapshot_(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<std::optional<QuotaSnapshot>> set_snapshot(std::optional<QuotaSnapshot> value) { auto raw = backend_.set_state("snapshot", detail::encode__Optional_QuotaSnapshot_(value)); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> std::optional<QuotaSnapshot> { return detail::decode__Optional_QuotaSnapshot_(raw.get()); }); }
  [[nodiscard]] std::uint64_t set_snapshot_async(std::optional<QuotaSnapshot> value, std::function<void(Result<std::optional<QuotaSnapshot>>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.set_state_async("snapshot", detail::encode__Optional_QuotaSnapshot_(value), [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<std::optional<QuotaSnapshot>> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode__Optional_QuotaSnapshot_(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }

 private:
  rivet::linux_runtime::Backend& backend_;
};

}  // namespace rivet_app
